(deftheme se7entyse7en "my custom theme")
(custom-theme-set-faces
  'se7entyse7en
  '(default ((t (:foreground "#2980b9" :background "#070707"))))
  '(cursor ((t (:background "#2ecc71"))))
  '(fringe ((t (:background "#141729"))))
  '(mode-line ((t (:foreground "#8791de" :background "#1a2432"))))
  '(region ((t (:background "#16a085"))))
  '(font-lock-builtin-face ((t (:foreground "#e23262"))))
  '(font-lock-comment-face ((t (:foreground "##f1c40f"))))
  '(font-lock-function-name-face ((t (:foreground "#f39c12"))))
  '(font-lock-keyword-face ((t (:foreground "#9b59b6"))))
  '(font-lock-string-face ((t (:foreground "#27ae60"))))
  '(font-lock-type-face ((t (:foreground"#e67e22"))))
  '(font-lock-constant-face ((t (:foreground "#ed4f45"))))
  '(font-lock-variable-name-face ((t (:foreground "#2980b9"))))
  '(minibuffer-prompt ((t (:foreground "#89b4e1" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'se7entyse7en)
