(deftheme se7entyse7en "my custom theme")
(custom-theme-set-faces
  'se7entyse7en
  '(default ((t (:foreground "#4a95d3" :background "#07080e"))))
  '(cursor ((t (:background "#5dd93f"))))
  '(fringe ((t (:background "#141729"))))
  '(mode-line ((t (:foreground "#8791de" :background "#1a2432"))))
  '(region ((t (:background "#0d4519"))))
  '(font-lock-builtin-face ((t (:foreground "#e23262"))))
  '(font-lock-comment-face ((t (:foreground "#cbdf16"))))
  '(font-lock-function-name-face ((t (:foreground "#d2aa56"))))
  '(font-lock-keyword-face ((t (:foreground "#cf74d2"))))
  '(font-lock-string-face ((t (:foreground "#4fbb3e"))))
  '(font-lock-type-face ((t (:foreground"#f66c09"))))
  '(font-lock-constant-face ((t (:foreground "#ed4f45"))))
  '(font-lock-variable-name-face ((t (:foreground "#6098d7"))))
  '(minibuffer-prompt ((t (:foreground "#89b4e1" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'se7entyse7en)
